POST http://localhost:4001/patients
Content-Type: application/json

{
  "name": "Hazhir GRPC",
  "email": "hazhir73grpccc@gmail.com",
  "address": "tehran",
  "dateOfBirth": "1996-12-06",
  "registeredDate": "2025-04-22"
}